# Control file for continuous integration testing at http://travis-ci.org/

language: c
compiler:
  - clang
  - gcc

env:
  global:
    - HTSDIR=./htslib
    - PATH=$TRAVIS_BUILD_DIR/htslib:$PATH

matrix:
  include:
    # An unoptimised C99 build, for detecting non-static inline functions
    - compiler: gcc
      env: CFLAGS="-std=gnu99 -O0"

before_script:
  - git clone --depth=5 --branch=bcftools+calling git://github.com/samtools/htslib.git

script: make -e && make -e test
