# Control file for continuous integration testing at http://travis-ci.org/

language: c
compiler:
  - clang
  - gcc

install: git clone --depth=5 --branch=develop git://github.com/samtools/htslib.git
env: HTSDIR=./htslib

script: make -e && make -e test
