# Control file for continuous integration testing at http://travis-ci.org/

language: c
compiler:
  - clang
  - gcc

env:
  global:
    - HTSDIR=./htslib PATH=./tabix:$PATH

matrix:
  include:
    # An unoptimised C99 build, for detecting non-static inline functions
    - compiler: gcc
      env: CFLAGS="-std=gnu99 -O0"

before_script:
  - git clone --depth=5 --branch=develop git://github.com/samtools/htslib.git
  - git clone --depth=5 git://github.com/samtools/tabix.git && cd tabix && make && cd ..

script: make -e && make -e test
